version: "3.9"

services:
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql/mysql-server:latest
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    networks:
      - laravel

networks:
    laravel:
      driver: bridge

volumes:
  db-data: ~
